"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""

def show_versions():
    """
    Print system information and installed module versions.

    Examples
    --------

    ::

        $ python -c "import geopandas; geopandas.show_versions()"
    """
    ...
