"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
_multi_type_map = ...

def collect(x, multi=...):
    """
    Collect single part geometries into their Multi* counterpart

    Parameters
    ----------
    x : an iterable or Series of Shapely geometries, a GeoSeries, or
        a single Shapely geometry
    multi : boolean, default False
        if True, force returned geometries to be Multi* even if they
        only have one component.

    """
    ...
