blank_issues_enabled: false
contact_links:
  - name: CITS3200 Project Discussion
    url: https://github.com/zazwaz12/CITS3200---National-Housing-Simulation/wiki
    about: Please ask and answer questions here.

templates:
  - name: Internal Dev Issue
    about: Submit a request for new development/feature/bug
    file_name: development_request.md
    title: 'issue-<NUMBER>-<TITLE>'
    body:
      - type: markdown
        attributes:
          value: |
            # Issue
      - type: textarea
        id: problem
        attributes:
          label: Is your feature request related to a problem? Please describe.
          description: A clear and concise description of what the problem is.
        validations:
          required: true
      - type: markdown
        attributes:
          value: |
            ## Suggested Solution
      - type: textarea
        id: solution
        attributes:
          label: Describe the solution you'd like
          description: A clear and concise description of what you want to happen.
        validations:
          required: true
      - type: markdown
        attributes:
          value: |
            ## Alternatives Considered
      - type: textarea
        id: alternatives
        attributes:
          label: Describe alternatives you've considered
          description: A clear and concise description of any alternative solutions or features you've considered.
        validations:
          required: false
      - type: markdown
        attributes:
          value: |
            ## Additional context
      - type: textarea
        id: context
        attributes:
          label: Additional context
          description: Add any other context or screenshots about the feature request here.
        validations:
          required: false
