"""
This type stub file was generated by pyright.
"""

"""Vendored, cut down version of pyogrio/util.py for use with fiona"""

def vsi_path(path: str) -> str:
    """
    Ensure path is a local path or a GDAL-compatible vsi path.

    """
    ...

SCHEMES = ...
CURLSCHEMES = ...
