"""
This type stub file was generated by pyright.
"""

import geopandas as gpd
import geopandas.datasets
import numpy as np
import pandas as pd
from geopandas._config import options
from geopandas.array import points_from_xy
from geopandas.geodataframe import GeoDataFrame
from geopandas.geoseries import GeoSeries
from geopandas.io.arrow import _read_feather as read_feather
from geopandas.io.arrow import _read_parquet as read_parquet
from geopandas.io.file import _read_file as read_file
from geopandas.io.sql import _read_postgis as read_postgis
from geopandas.tools import clip, overlay, sjoin, sjoin_nearest
from geopandas.tools._show_versions import show_versions

from . import _version

"""
This type stub file was generated by pyright.
"""
__version__ = ...
