"""
This type stub file was generated by pyright.
"""

import pytest

"""
This type stub file was generated by pyright.
"""

@pytest.fixture(autouse=True)
def add_geopandas(doctest_namespace): ...
def pytest_configure(config): ...

has_sindex_backend = ...

def pytest_runtest_setup(item): ...
