"""
This type stub file was generated by pyright.
"""

import multiprocess as mp
import ppft as parallelpython
from multiprocess import cpu_count, freeze_support
from multiprocess.dummy import Pool as ThreadPool
from multiprocess.pool import Pool as ProcessPool
from pathos.pools import _clear as shutdown

from . import mp_helper, pp_helper
